databases:
  - name: schedules-db
    databaseName: schedules
    user: schedules_user
    plan: free
    region: oregon

services:
  - type: web
    name: schedules-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: schedules-db
          property: internalConnectionString
      - key: JWT_SECRET
        generateValue: true
